### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by baiRookie** [HuanTanSheng/EasyPhotos#1]
当我点击相册拒绝权限时，停留在相册页面，返回按钮无效

**Comment by HuanTanSheng** [comment]
@baiRookie 
你好，感谢你的反馈。
我已经修复了该问题，请使用1.3.3-alpha-11版本。
但是alpha版本在升级正式版后我会删除，你可以加我微信：huantansheng
这样我删除之前就可以通知你，以免给你造成不必要的麻烦。
如果你不想用这个版本（毕竟是alpha版本，同时缺少wiki注释），我看你fork了EasyPhotos，其实改起来也很简单，返回按钮的id是iv_back，只需要在EasyPhotosActivity这个类里面把设置监听放在权限处理之前。或者在activity_easy_photos.xml文件中的返回按钮控件中添加：android:onClick="onClick"
当然，你可能早就解决好了，只是来提醒我一下而已，所以还是要感谢你，哈哈。
最后，再次感谢你的反馈，这个对我来说真的很重要~
