### ISSUE TITLE
图库视频选择

### ISSUE THREAD

**Issue by yuzeGitHub** [HuanTanSheng/EasyPhotos#108]
能否新增一个图库里有图片和视频,选择了图片就不能选择视频,选择视频只能选择一个视频的功能

**Comment by HuanTanSheng** [comment]
目前是支持这个功能的，想看Wiki

**Comment by yuzeGitHub** [comment]
您好,目前支持的功能是图库里面是有图片和视频的,但是图片和视频能同时选择,还有视频能选择,我想的是视频图片共存,选择了图片就不能选择视频,如果选择了视频就不能选择图片,而且视频只能选择一个!非常感谢!


yuze.tang@aliyun.com
 
发件人： 桓谭生
发送时间： 2020-01-13 14:47
收件人： HuanTanSheng/EasyPhotos
抄送： yuzeGitHub; Author
主题： Re: [HuanTanSheng/EasyPhotos] 图库视频选择 (#108)
目前是支持这个功能的，想看Wiki

**Comment by HuanTanSheng** [comment]
明白了，这个有点费时间哦，我现在公司任务比较重，要过一段时间才能处理呢

**Comment by yuzeGitHub** [comment]
没事,只是有这么个需求,就是希望有这么个功能,等有时间弄就好,非常感谢!



yuze.tang@aliyun.com
 
发件人： 桓谭生
发送时间： 2020-01-15 10:25
收件人： HuanTanSheng/EasyPhotos
抄送： yuzeGitHub; Author
主题： Re: [HuanTanSheng/EasyPhotos] 图库视频选择 (#108)
明白了，这个有点费时间哦，我现在公司任务比较重，要过一段时间才能处理呢

**Comment by cxmmxc** [comment]
为何你的需求跟我项目的需求如此相似。。。。
我的也是最多选3个文件（最多1个视频或者没有视频）。
这个好弄，不要依赖中央仓库，直接把他的lib拷过去，自己改源码就行

**Comment by yuzeGitHub** [comment]
好的,暂时可以改一下源码,我觉得这个功能要是能灵活配置的话,在以后的开发中会很方便,所以等您有时间的时候还是想让您修改一下,方便以后的使用,非常感谢!



yuze.tang@aliyun.com
 
发件人： cxmmxc
发送时间： 2020-01-16 11:18
收件人： HuanTanSheng/EasyPhotos
抄送： yuzeGitHub; Author
主题： Re: [HuanTanSheng/EasyPhotos] 图库视频选择 (#108)
为何你的需求跟我项目的需求如此相似。。。。
我的也是最多选3个文件（最多1个视频或者没有视频）。
这个好弄，不要依赖中央仓库，直接把他的lib拷过去，自己改源码就行

**Comment by Hy-Wang777** [comment]
老哥 现在这个功能实装了吗

**Comment by HuanTanSheng** [comment]
记录一下，3.1.0版本更新后，如果稳定，就做这个

**Comment by HuanTanSheng** [comment]
已添加该功能，详情请看3.1.0版本更新信息
