### ISSUE TITLE
手机开发者选项选择不保留活动，拍照出现问题

### ISSUE THREAD

**Issue by pengjunhong** [HuanTanSheng/EasyPhotos#110]
不保留活动开启后，到拍照页面之前的页面都会被回收掉，当拍照完成返回回调时，会因为页面都是重新加载的而出问题。这样就引入这样一个场景，当某个页面比较复杂时，页面已经内存紧张，那么这个时候调用拍照功能，就会出现页面会回收，从而引发一系列问题。

**Comment by HuanTanSheng** [comment]
不保留活动是指离开活动界面即销毁活动，因为被销毁了所以返回时重建界面没有接收到数据。这与框架本身无关。

**Comment by pengjunhong** [comment]
这个只是模拟在手机运行内存低的情况。

**Comment by HuanTanSheng** [comment]
好的
