### ISSUE TITLE
华为p30手机第一次打开相册显示不全，多次打开才可以

### ISSUE THREAD

**Issue by Qiang11** [HuanTanSheng/EasyPhotos#111]
华为p30手机第一次打开相册显示不全，多次打开才可以，版本3.0.3

**Comment by HuanTanSheng** [comment]
判断是因为图片过万张以上导致，可加交流群交流288600953

**Comment by callhh** [comment]
> 判断是因为图片过万张以上导致，可加交流群交流288600953

android10的兼容问题还是很多的。比如在相册里面点图片想预览，也是黑色的

**Comment by HuanTanSheng** [comment]
不会啊，用demo也会这样？
