### ISSUE TITLE
PNG格式的图片，选择后返回的Photos里的图片宽高都为0

### ISSUE THREAD

**Issue by XuQK** [HuanTanSheng/EasyPhotos#112]
有什么解决办法吗

**Comment by HuanTanSheng** [comment]
你这个应该是个例，正常情况不会这样的。麻烦提供更加详细的信息，如手机机型、图片来源等，建议加入QQ交流群交流288600953

**Comment by XuQK** [comment]
[归档2.zip](https://github.com/HuanTanSheng/EasyPhotos/files/4052378/2.zip)

图片如上，机型一加6 Android10，图片来源：某壁纸网站。
QQ群就免了，好久没用过了，微信群可以加哈哈

**Comment by HuanTanSheng** [comment]
你相册里能看到图片的宽高么

**Comment by XuQK** [comment]
是指系统相册？可以的

**Comment by HuanTanSheng** [comment]
我这里没问题，我是直接把你的图片从电脑拖进了手机，显示正常，数据也正常，你是如何操作的？

**Comment by XuQK** [comment]
第一张图是Pixel3 Android10
第二张图是一加6 Android10
都是用的直接下载下来的demo打开的，看宽高，都是0，用的图就是我上面发的压缩包里的，直接拖进手机的。

![Screenshot_20200113-161234](https://user-images.githubusercontent.com/2867860/72241276-5ff60200-3621-11ea-8c96-f17a1f87c57a.jpg)
![WechatIMG217](https://user-images.githubusercontent.com/2867860/72241278-5ff60200-3621-11ea-982e-2b5b00788801.jpeg)

**Comment by HuanTanSheng** [comment]
因为我这里没有这两个机型，所以需要跟你确认一下。

**Comment by HuanTanSheng** [comment]
是所有图片都获取不到宽高么？还是只有从电脑里拖到手机的图片才获取不到宽高呢？

**Comment by XuQK** [comment]
同一个网站下载的同一批壁纸图片，有JPG和PNG，JPG的能正常获取到，PNG的不行，二者都是从PC通过数据线到手机上的

**Comment by XuQK** [comment]
emmmm，还是这个一加6，照相机照出来的照片，不管看起来是宽高是哪个大，在该项目的demo里看起来，一律是宽>高

**Comment by pengjunhong** [comment]
大兄弟 我这边也有用户遇到获取宽高是0得，但是手头没有这些机型，你那边能不能帮忙测试下，使用别得框架是否也有这个问题，如果没有 那么问题就可以定位在获取图片宽高那边了。

**Comment by pengjunhong** [comment]
@XuQK 大兄弟 我这边也有用户遇到获取宽高是0得，但是手头没有这些机型，你那边能不能帮忙测试下，使用别得框架是否也有这个问题，如果没有 那么问题就可以定位在获取图片宽高那边了。

**Comment by XuQK** [comment]
项目是通过MediaStore去获取数据库中的图片宽高的，所以外来图片在有的ROM上是会有宽高为0的情况，本机相机拍摄的图片也会有宽高相反的情况。

**Comment by XuQK** [comment]
大佬这问题还修不修呀

**Comment by HuanTanSheng** [comment]
不好意思，从上次聊完这段时间一直996，等忙完立刻处理！

**Comment by HuanTanSheng** [comment]
已合并代码并发版，感谢工鞋
