### ISSUE TITLE
AS3.6.1导入有问题

### ISSUE THREAD

**Issue by agan112** [HuanTanSheng/EasyPhotos#118]
尊敬的EasyPhotos开发者，你好：

经过调研之后发现你的开源项目做得很不错，现在想要试试效果，但是导入的时候出现了以下问题，希望你可以抽时间解决一下，谢谢：

导入方式：
implementation 'com.github.HuanTanSheng:EasyPhotos:3.0.4'

提示错误：
ERROR: Failed to resolve: com.android.support:exifinterface:24.2.1

**Comment by HuanTanSheng** [comment]
3.0.4不支持support，是android x的。
