### ISSUE TITLE
onActivityResult 返回的Photo的uri是null，但是有path

### ISSUE THREAD

**Issue by wanyt** [HuanTanSheng/EasyPhotos#119]
为啥uri是null.

**Comment by HuanTanSheng** [comment]
请问是最新版本么？

**Comment by wanyt** [comment]
是最新版本，该配置的权限都配置了

**Comment by wangfeigit** [comment]
这个问题解决了吗，我也遇到了

**Comment by wanyt** [comment]
目前还没有解决。当时我是想通过EasyPhoto获取图片的uri，然后跳转到系统的剪裁图片。结果发现部分机型uri是null，我的解决办法是不跳转到系统的剪裁图片，使用了第三方的剪裁图片库，虽然uri是null，但是图片路径可以获取到，返回后拿着图片路径跳转了三方的剪裁图片了。

**Comment by mlp1995** [comment]
有path 是不是可以尝试将path 转成 uri   呢

**Comment by HuanTanSheng** [comment]
@wanyt @wangfeigit 请问具体机型是什么？另外是这个机型的所有图片都这样还是某个图片？

**Comment by HuanTanSheng** [comment]
已做了修复，如果方便的滑，希望能够加入QQ交流群288600953验证一下，感谢。
