### ISSUE TITLE
requestLegacyExternalStorage策略马上不能用了

### ISSUE THREAD

**Issue by baiyuliang** [HuanTanSheng/EasyPhotos#127]
requestLegacyExternalStorage策略马上不能用了，希望作者能真正兼容10.0及以上系统，否则后期修改成本较高

**Comment by HuanTanSheng** [comment]
除了拼图都已经真正兼容了啊，还有哪里没兼容到么？

**Comment by HuanTanSheng** [comment]
另外近期都会很忙，如果你能贡献一些兼容代码，我会检验后融合

**Comment by baiyuliang** [comment]
> 除了拼图都已经真正兼容了啊，还有哪里没兼容到么？

因为我看到您使用的是requestLegacyExternalStorage策略来兼容10.0，这个策略有风险，马上不能使用了，安卓11已经禁止此策略

**Comment by HuanTanSheng** [comment]
哦，我是用的uri的方式兼容的10.0
