### ISSUE TITLE
启动不了相册，initSomeViews()方法调用报空指针

### ISSUE THREAD

**Issue by zhrxcs** [HuanTanSheng/EasyPhotos#133]
解决：自己的布局文件activity_easy_photos与easyphotos内布局重名产生冲突

**Comment by HuanTanSheng** [comment]
如果是因为重名导致的错误，建议改名

**Comment by zhrxcs** [comment]
已改，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"桓谭生"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月2日(星期二) 下午3:16
收件人:&nbsp;"HuanTanSheng/EasyPhotos"<EasyPhotos@noreply.github.com&gt;;
抄送:&nbsp;"星辰杀"<2550850230@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [HuanTanSheng/EasyPhotos] 启动不了相册，initSomeViews()方法调用报空指针 (#133)





 
如果是因为重名导致的错误，建议改名
