### ISSUE TITLE
未找到3.0.6版本

### ISSUE THREAD

**Issue by IAmWilling** [HuanTanSheng/EasyPhotos#135]
`implementation 'com.github.HuanTanSheng:EasyPhotos:3.0.6'`
![W8FW1_G{P30V(U2U7LW)LI3](https://user-images.githubusercontent.com/39398882/83999402-40c38c80-a995-11ea-89fa-742db7e32817.png)

Failed to resolve: com.github.HuanTanSheng:EasyPhotos:3.0.6
Show in Project Structure dialog
Affected Modules: app

**Comment by hd119476** [comment]
有加入這個嗎 -->  maven { url "https://jitpack.io" }
