### ISSUE TITLE
ANR：部分手机一打开相册选择照片就直接卡死

### ISSUE THREAD

**Issue by LG12300** [HuanTanSheng/EasyPhotos#139]
EasyPhoto版本：3.0.6
用户机型：华为 JEF AN00
![其他数据](https://user-images.githubusercontent.com/49315781/86552181-cf6a0000-bf79-11ea-9172-c788b7487214.png)

**Comment by LG12300** [comment]
回退到了3.0.5，ANR更多了
Input dispatching timed out
ANR Input dispatching timed out (Waiting to send non-key event because the touched window has not finished processing certain input events that were delivered to it over 500.0ms ago. waitqueue length = 3, head.seq = 14638594, Wait queue head age: 10580.7ms.)

com.huantansheng.easyphotos.i.c.a.f(BitmapUtils.java:4)

**Comment by lovelyelfpop** [comment]
都说 华为出现的BitmapUtils 问题是 系统底层问题，有很长时间了，华为系统不改进，上层应用都没有办法。只能用系统图库了

**Comment by LG12300** [comment]
> 都说华为出现的BitmapUtils问题是系统严重问题，有很长时间了，华为系统不改进，上层应用都没有办法。只能用系统图库了

我扛不住了，项目里只有这个导致崩溃和anr，而且用户最多的就是华为渠道，只能忍痛用系统的了
