### ISSUE TITLE
刚搜到的 demo 和 功能都看了  但是...............

### ISSUE THREAD

**Issue by yuxuhao** [HuanTanSheng/EasyPhotos#140]
大兄弟 再加一个 图片剪裁是不是会有那么一丝丝的惊喜呢

**Comment by HuanTanSheng** [comment]
@yuxuhao  图片裁剪用Ucrop更好哦。我这个集成一下也没必要，就算集成进来了，你调用时是一样的，而我又不能经常关注Ucrop的更新情况，其实集成了对你来说，更不好。
