### ISSUE TITLE
Dear Author , my problem is android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.tttt.pic.models.album.entity.Photo

### ISSUE THREAD

**Issue by Timan86** [HuanTanSheng/EasyPhotos#147]
I ActivityTaskManager: START u0 {cmp=com.tttt.pic/.ui.edit.ImageEditActivity (has extras)} from uid 11289
10-14 11:29:30.023  6509  7497 E Parcel  : Class not found when unmarshalling: com.tttt.pic.models.album.entity.Photo
10-14 11:29:30.023  6509  7497 E Parcel  : java.lang.ClassNotFoundException: com.tttt.pic.models.album.entity.Photo
10-14 11:29:30.023  6509  7497 E Parcel  : 	at java.lang.Class.classForName(Native Method)
10-14 11:29:30.023  6509  7497 E Parcel  : 	at java.lang.Class.forName(Class.java:454)
10-14 11:29:30.023  6509  7497 E Parcel  : 	at android.os.Parcel.readParcelableCreator(Parcel.java:3031)
10-14 11:29:30.023  6509  7497 E Parcel  : 	at android.os.Parcel.readParcelable(Parcel.java:2981)
10-14 11:29:30.023  6509  7497 E Parcel  : 	at android.os.Parcel.readValue(Parcel.java:2883)
10-14 11:29:30.023  6509  7497 E Parcel  : 	at android.os.Parcel.readListInternal(Parcel.java:3324)
10-14 11:29:30.023  6509  7497 E Parcel  : 	at android.os.Parcel.readArrayList(Parcel.java:2467)
10-14 11:29:30.023  6509  7497 E Parcel  : 	at android.os.Parcel.readValue(Parcel.java:2904)
10-14 11:29:30.023  6509  7497 E Parcel  : 	at android.os.Parcel.readArrayMapInternal(Parcel.java:3261)
10-14 11:29:30.023  6509  7497 E Parcel  : 	at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
10-14 11:29:30.023  6509  7497 E Parcel  : 	at android.os.BaseBundle.unparcel(BaseBundle.java:236)
10-14 11:29:30.023  6509  7497 E Parcel  : 	at android.os.BaseBundle.getString(BaseBundle.java:1160)
10-14 11:29:30.023  6509  7497 E Parcel  : 	at android.content.Intent.getStringExtra(Intent.java:8548)
10-14 11:29:30.023  6509  7497 E Parcel  : 	at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:794)
10-14 11:29:30.023  6509  7497 E Parcel  : 	at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:698)
10-14 11:29:30.023  6509  7497 E Parcel  : 	at com.android.server.wm.ActivityStarter.startActivityMayWait(ActivityStarter.java:1926)
10-14 11:29:30.023  6509  7497 E Parcel  : 	at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:629)
10-14 11:29:30.023  6509  7497 E Parcel  : 	at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1706)
10-14 11:29:30.023  6509  7497 E Parcel  : 	at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1602)
10-14 11:29:30.023  6509  7497 E Parcel  : 	at com.android.server.wm.ActivityTaskManagerService.startActivity(ActivityTaskManagerService.java:1556)
10-14 11:29:30.023  6509  7497 E Parcel  : 	at android.app.IActivityTaskManager$Stub.onTransact(IActivityTaskManager.java:1681)
10-14 11:29:30.023  6509  7497 E Parcel  : 	at android.os.Binder.execTransactInternal(Binder.java:1021)
10-14 11:29:30.023  6509  7497 E Parcel  : 	at android.os.Binder.execTransact(Binder.java:994)
10-14 11:29:30.023  6509  7497 E Parcel  : Caused by: java.lang.ClassNotFoundException: com.tw.picedit.models.album.entity.Photo
10-14 11:29:30.023  6509  7497 E Parcel  : 	... 23 more
10-14 11:29:30.023  6509  7497 W Bundle  : Failed to parse Bundle, but defusing quietly
10-14 11:29:30.023  6509  7497 W Bundle  : android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.tw.picedit.models.album.entity.Photo
10-14 11:29:30.023  6509  7497 W Bundle  : 	at android.os.Parcel.readParcelableCreator(Parcel.java:3059)
10-14 11:29:30.023  6509  7497 W Bundle  : 	at android.os.Parcel.readParcelable(Parcel.java:2981)
10-14 11:29:30.023  6509  7497 W Bundle  : 	at android.os.Parcel.readValue(Parcel.java:2883)
10-14 11:29:30.023  6509  7497 W Bundle  : 	at android.os.Parcel.readListInternal(Parcel.java:3324)
10-14 11:29:30.023  6509  7497 W Bundle  : 	at android.os.Parcel.readArrayList(Parcel.java:2467)
10-14 11:29:30.023  6509  7497 W Bundle  : 	at android.os.Parcel.readValue(Parcel.java:2904)
10-14 11:29:30.023  6509  7497 W Bundle  : 	at android.os.Parcel.readArrayMapInternal(Parcel.java:3261)
10-14 11:29:30.023  6509  7497 W Bundle  : 	at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
10-14 11:29:30.023  6509  7497 W Bundle  : 	at android.os.BaseBundle.unparcel(BaseBundle.java:236)
10-14 11:29:30.023  6509  7497 W Bundle  : 	at android.os.BaseBundle.getString(BaseBundle.java:1160)
10-14 11:29:30.023  6509  7497 W Bundle  : 	at android.content.Intent.getStringExtra(Intent.java:8548)
10-14 11:29:30.023  6509  7497 W Bundle  : 	at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:794)
10-14 11:29:30.023  6509  7497 W Bundle  : 	at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:698)
10-14 11:29:30.023  6509  7497 W Bundle  : 	at com.android.server.wm.ActivityStarter.startActivityMayWait(ActivityStarter.java:1926)
10-14 11:29:30.023  6509  7497 W Bundle  : 	at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:629)
10-14 11:29:30.023  6509  7497 W Bundle  : 	at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1706)
10-14 11:29:30.023  6509  7497 W Bundle  : 	at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1602)
10-14 11:29:30.023  6509  7497 W Bundle  : 	at com.android.server.wm.ActivityTaskManagerService.startActivity(ActivityTaskManagerService.java:1556)
10-14 11:29:30.023  6509  7497 W Bundle  : 	at android.app.IActivityTaskManager$Stub.onTransact(IActivityTaskManager.java:1681)
10-14 11:29:30.023  6509  7497 W Bundle  : 	at android.os.Binder.execTransactInternal(Binder.java:1021)
10-14 11:29:30.023  6509  7497 W Bundle  : 	at android.os.Binder.execTransact(Binder.java:994)

**Comment by Timan86** [comment]
混淆使用如下：
-keep class * implements android.os.Parcelable {
  public static final android.os.Parcelable$Creator *;
}

**Comment by HuanTanSheng** [comment]
-keep class com.tttt.pic.models.album.entity.**{ *; }

or

-keep class * implements android.os.Parcelable {
  public static final android.os.Parcelable$Creator *;
}
-keepclassmembers class * implements android.os.Parcelable {
 public <fields>;
 private <fields>;
protected <fields>;
private static final <fields>;
}
