### ISSUE TITLE
android R 版本下对选择的图片 uri进行剪裁 会报此图片不可编辑

### ISSUE THREAD

**Issue by zhaocongqing** [HuanTanSheng/EasyPhotos#149]
选择的图片： Photo{name='IMG_20201029_062718.jpg', uri='content://media/external/images/media/58', path='/storage/emulated/0/Pictures/IMG_20201029_062718.jpg', time=1603952839', minWidth=960', minHeight=1280}

系统剪裁代码：
public void headRouteToCrop(Activity context, Uri uri, String cropImageName) {
        Intent intent = new Intent("com.android.camera.action.CROP");
        intent.setDataAndType(uri, "image/*");
        intent.putExtra("crop", true);
        intent.putExtra("aspectX", 400);
        intent.putExtra("aspectY", 400);
        intent.putExtra("return-data", false);
        intent.putExtra(MediaStore.EXTRA_OUTPUT, Uri.fromFile(
                new File(cropImageName)));
        intent.addFlags(Intent.FLAG_GRANT_WRITE_URI_PERMISSION
                | Intent.FLAG_GRANT_READ_URI_PERMISSION);
        context.startActivityForResult(intent, Constants.REQUEST_CODE.CROP_IMAGE);
    }

**Comment by HuanTanSheng** [comment]
android R裁剪图片（其实就是图片写入）需要写入权限，createWriteRequest() ，建议百度查一下具体代码，因与本框架无关，我就关闭问题了哈。
