### ISSUE TITLE
安卓10 拍照一直提示照片保存中，请稍后。拍完照没反应，没有✔那个按钮

### ISSUE THREAD

**Issue by Founder005** [HuanTanSheng/EasyPhotos#150]
日志 如下：
 E/libc: Access denied finding property "vendor.camera.hal1.packagelist"
 E/CheckPermission: camera-code= 5
权限是已经获取过的

**Comment by Founder005** [comment]
Demo也报错了，拍照完成点击对号，提示的是cancel，我的是oppo Reno4测试机，同事的荣耀 安卓也报错

**Comment by HuanTanSheng** [comment]
已修复，感谢反馈。
