### ISSUE TITLE
EasyPhotosActivity偶发ANR  [版本3.06，华为P30 pro]

### ISSUE THREAD

**Issue by syl1207** [HuanTanSheng/EasyPhotos#154]
2020-11-18 15:34:29.926 1329-1802/system_process E/ActivityManager: ANR in com.song.project.sc (com.song.project.sc/com.huantansheng.easyphotos.ui.EasyPhotosActivity)
    PID: 17813
    Reason: Input dispatching timed out (Waiting to send non-key event because the touched window has not finished processing certain input events that were delivered to it over 500.0ms ago. waitqueue length = 5, head.seq = 3225095, Wait queue head age: 5509.4ms.)
    Parent: com.song.project.sc/com.huantansheng.easyphotos.ui.EasyPhotosActivity
    Load: 0.0 / 0.0 / 0.0
    CPU usage from 3486ms to -6790ms ago (2020-11-18 15:34:19.568 to 2020-11-18 15:34:29.845):
      29% 1329/system_server: 22% user + 7.8% kernel / faults: 3298 minor 24 major
      16% 21406/android.process.media: 0.4% user + 16% kernel / faults: 1588 minor 2 major
      8.5% 881/hwpged: 0% user + 8.5% kernel
      7.3% 2427/com.android.phone: 5.5% user + 1.8% kernel / faults: 4805 minor
      2.8% 800/aptouch_daemon: 2.4% user + 0.3% kernel
      2.4% 17813/com.cmos.cloud.center.sc: 1.5% user + 0.8% kernel / faults: 4228 minor 70 major
      2.3% 1/init: 1.4% user + 0.8% kernel / faults: 11 minor
      2.3% 14550/com.tencent.mm:push: 1.1% user + 1.1% kernel / faults: 3314 minor 14 major
      2.2% 476/logd: 0.8% user + 1.3% kernel / faults: 14 minor
      2% 29662/com.huawei.intelligent:intelligentService: 1.4% user + 0.5% kernel / faults: 3608 minor 28 major
      1.9% 21485/adbd: 0.3% user + 1.5% kernel / faults: 31 minor
      1.8% 17647/kworker/u16:14: 0% user + 1.8% kernel
      1.5% 479/servicemanager: 0.3% user + 1.1% kernel / faults: 1 minor
      1.5% 883/rild: 0.7% user + 0.7% kernel / faults: 3 minor
      1.4% 723/surfaceflinger: 0.8% user + 0.5% kernel / faults: 43 minor
      0.4% 17648/kworker/u16:15: 0% user + 0.4% kernel
      0.5% 1688/kworker/u16:25: 0% user + 0.5% kernel
      1.3% 2018/com.huawei.recsys: 1.3% user + 0% kernel / faults: 155 minor
      1.2% 1983/com.android.systemui: 0.6% user + 0.5% kernel / faults: 879 minor
      1.1% 21218/kworker/u16:2: 0% user + 1.1% kernel
      1% 2366/com.huawei.systemserver: 0.4% user + 0.5% kernel / faults: 422 minor
      0.9% 2673/com.huawei.HwNaturalBase: 0.4% user + 0.4% kernel / faults: 2408 minor 15 major
      0.4% 25954/com.huawei.health:DaemonService: 0.3% user + 0% kernel / faults: 581 minor
      0.8% 896/hiview: 0.2% user + 0.5% kernel / faults: 611 minor 1 major
      0.2% 2589/com.huawei.android.ds: 0.1% user + 0.1% kernel / faults: 1565 minor
      0.8% 8133/kworker/u16:0: 0% user + 0.8% kernel
      0.7% 643/netd: 0% user + 0.6% kernel / faults: 669 minor
      0.7% 686/android.hardware.graphics.composer@2.2-service: 0.2% user + 0.4% kernel / faults: 3 minor
      0.7% 2332/com.huawei.hiview: 0.4% user + 0.2% kernel / faults: 565 minor
      0.7% 21324/chargelogcat-c: 0% user + 0.7% kernel
      0.7% 23575/logcat: 0.1% user + 0.5% kernel / faults: 3 minor
      0.6% 272/irq/191-thp: 0% user + 0.6% kernel
      0.6% 2406/com.huawei.iaware: 0.3% user + 0.2% kernel / faults: 314 minor
      0.5% 661/AppDS: 0% user + 0.5% kernel
      0.5% 13243/com.tencent.mobileqq:mini: 0.3% user + 0.1% kernel / faults: 67 minor 1 major
      0.5% 28638/com.android.mms: 0.3% user + 0.1% kernel / faults: 519 minor
      0.4% 9/rcu_preempt: 0% user + 0.4% kernel
      0% 20532/kworker/6:1: 0% user + 0% kernel
      0.4% 22177/kworker/3:1: 0% user + 0.4% kernel
      0.4% 23193/com.huawei.lbs: 0.2% user + 0.1% kernel / faults: 381 minor
      0.4% 23552/kworker/2:0: 0% user + 0.4% kernel
      0.3% 725/powerlogd: 0.2% user + 0% kernel
      0.3% 862/dubaid: 0.2% user + 0% kernel
      0.3% 2149/com.huawei.systemmanager:service: 0.1% user + 0.1% kernel / faults: 61 minor
      0.1% 3942/com.huawei.android.pushagent.PushService: 0% user + 0.1% kernel / faults: 189 minor 1 major
      0.3% 12681/com.tencent.mobileqq: 0.1% user + 0.1% kernel / faults: 464 minor
      0.3% 14298/com.huawei.himovie: 0.1% user + 0.1% kernel / faults: 8 minor
      0.3% 14425/com.tencent.mm: 0% user + 0.2% kernel / faults: 753 minor 14 major
      0.3% 14436/com.huawei.himovie:player: 0% user + 0.2% kernel / faults: 3 minor
      0.1% 21771/kworker/4:2: 0% user + 0.1% kernel
      0.3% 23185/kworker/0:1: 0% user + 0.3% kernel
      0.2% 91/spi3: 0% user + 0.2% kernel

**Comment by zhouzl18** [comment]
我的荣耀20也遇到了这种情况。

**Comment by HuanTanSheng** [comment]
@syl1207 @zhouzl18 已修复，若方便，希望可以到交流群288600953中参与测试确认，感谢。
