### ISSUE TITLE
希望新增仿微信图片编辑功能

### ISSUE THREAD

**Issue by MasterLinZj** [HuanTanSheng/EasyPhotos#160]
图片裁剪、涂鸦、马赛克、标注等等。

**Comment by HuanTanSheng** [comment]
@MasterLinZj 计划中是有的，只是实在抽不出精力， 只能先把核心功能完善好，适配好，然后再做了。

**Comment by MasterLinZj** [comment]
理解，为作者的无私精神点赞，好样的，加油！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HuanTanSheng/EasyPhotos"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月3日(星期三) 下午4:44
收件人:&nbsp;"HuanTanSheng/EasyPhotos"<EasyPhotos@noreply.github.com&gt;;
抄送:&nbsp;"小林掌柜"<1368402690@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [HuanTanSheng/EasyPhotos] 希望新增仿微信图片编辑功能 (#160)





 
@MasterLinZj 计划中是有的，只是实在抽不出精力， 只能先把核心功能完善好，适配好，然后再做了。

**Comment by HuanTanSheng** [comment]
@MasterLinZj 笔芯
