### ISSUE TITLE
相册照片多的时候打开相册要10s以上，就这一点基本废了

### ISSUE THREAD

**Issue by hukejia** [HuanTanSheng/EasyPhotos#162]

**Comment by hukejia** [comment]
排查发现，耗时的是这个 File file = new File(path);
                if (!file.exists() || !file.isFile()) {
                   continue;
                }

**Comment by leeManong** [comment]
> 排查发现，耗时的是这个 File file = new File(path);
> if (!file.exists() || !file.isFile()) {
> continue;
> }

android11下这个方法非常耗时。

**Comment by HuanTanSheng** [comment]
@hukejia @leeManong 感谢反馈，已做修改，不知二位是否方便加一下QQ群288600953，帮忙做个测试

**Comment by HuanTanSheng** [comment]
已确认修复
