### ISSUE TITLE
希望适配android11

### ISSUE THREAD

**Issue by ouyangmingzhuanyong** [HuanTanSheng/EasyPhotos#164]
targetSdkVersion设为30，无法打开相机

**Comment by 15010487565** [comment]
我现在的targetSdkVersion为30，测试机为小米和一加，android版本都是11.小米可以打开相机，一加不行

**Comment by ouyangmingzhuanyong** [comment]
> 我现在的targetSdkVersion为30，测试机为小米和一加，android版本都是11.小米可以打开相机，一加不行

![image](https://user-images.githubusercontent.com/12842991/107168020-71146c80-69f5-11eb-8693-240ac684d43c.png)
其实是  if (cameraIntent.resolveActivity(getPackageManager()) != null) {这句走了else方法，


解决方法
在清单文件中添加queries标签。Tip:启动第三方的app也是通过这种方式。
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.lib.image">
	
    <queries>
        <intent>
            <action android:name="android.media.action.IMAGE_CAPTURE"/>
        </intent>

        <intent>
            <action android:name="android.media.action.VIDEO_CAPTURE"/>
        </intent>
    </queries>    
</manifest>

**Comment by HuanTanSheng** [comment]
已修复
