### ISSUE TITLE
1200+张图片的时候，加载loading时间过长，而且存在部分图片不显示的情况

### ISSUE THREAD

**Issue by xprhs** [HuanTanSheng/EasyPhotos#167]

**Comment by HuanTanSheng** [comment]
你好，请问是什么机型，andorid版本号是多少？

**Comment by hweilong** [comment]
我也有这种情况，android 10 HUAWEI MATE20

**Comment by xprhs** [comment]
android 10 任意机型

**Comment by HuanTanSheng** [comment]
@hweilong @xprhs 最新的demo吗？群里测试已经没问题了呀，要不二位加一下群？这样交流不如群交流便捷呀。QQ群号：288600953

**Comment by HuanTanSheng** [comment]
已修复，原因是10不能用path判断文件在不在，官方让用uri判断，结果用uri判断的结果就是卡出翔。改进方案是对10进行不分区处理，依然用path判断。已经过测试。

**Comment by xprhs** [comment]
是的，已经申请入群
