### ISSUE TITLE
手机图片超过1000张后出现页面卡死情况

### ISSUE THREAD

**Issue by guiguzixiansheng** [HuanTanSheng/EasyPhotos#168]
手机图片超过1000张后出现页面卡死情况

**Comment by HuanTanSheng** [comment]
你好，请问是最新的demo吗？如果不是，麻烦用最新的。如果是，请留下手机型号及android版本号，感谢

**Comment by HuanTanSheng** [comment]
你好，请问是最新的demo吗？如果不是，麻烦用最新的。如果是，请留下手机型号及android版本号，感谢

**Comment by HuanTanSheng** [comment]
你好，还在么？

**Comment by HuanTanSheng** [comment]
经群里用户多次测试反馈，目前版本并无此问题，应该是你用的不是最新的demo，所以先关闭了。如有问题可以来Q群288600953交流，感谢。

**Comment by guiguzixiansheng** [comment]
我加下你们群
