### ISSUE TITLE
单独使用拍照时报错

### ISSUE THREAD

**Issue by iwhoophui** [HuanTanSheng/EasyPhotos#169]
AlbumModel.getInstance().getProjections()获取出来时null，导致boolean shouldReadWidth = projections.length > 8;报空指针，EasyPhotosActivity 510行

**Comment by iwhoophui** [comment]
<img width="735" alt="image" src="https://user-images.githubusercontent.com/22000078/112110670-3570e300-8bee-11eb-89c4-c0f98804604b.png">

**Comment by HuanTanSheng** [comment]
感谢反馈，在修复中，稍后更新

**Comment by iwhoophui** [comment]
已解决，但是直接启动相机拍照完成返回之后会先返回图片选择界面然后再关闭返回，这样体验感感觉不是很好

**Comment by HuanTanSheng** [comment]
这是因为相机拍照后，我们还要对图片数据进行一些数据获取工作，之后的版本考虑一下如何无感过度，比如在只启动相机后，把所有view都gone掉，然后做个透明背景。也可能是其他方案，我需要想一想，等下一个大版本一起解决
