### ISSUE TITLE
这个库很强大，有没有拍视频功能

### ISSUE THREAD

**Issue by zs18340282344** [HuanTanSheng/EasyPhotos#170]

**Comment by HuanTanSheng** [comment]
暂时不能

**Comment by zs18340282344** [comment]
以后会更新吗?



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年3月29日(星期一) 上午9:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [HuanTanSheng/EasyPhotos] 这个库很强大，有没有拍视频功能 (#170)





 
暂时不能

**Comment by HuanTanSheng** [comment]
有可能，但半年内肯定不会
