### ISSUE TITLE
leakcanary检测到内存泄漏

### ISSUE THREAD

**Issue by zhpanvip** [HuanTanSheng/EasyPhotos#171]
leakcanary检测EasyPhotosActivity中由Toast引起的内存泄漏问题，建议可以添加一个Toast工具类，初始化参数使用ApplicationContext。

**Comment by HuanTanSheng** [comment]
反写反馈，请问方便把泄露信息截图发过来吗？

**Comment by HuanTanSheng** [comment]
或者加一下Q群288600953

**Comment by zhpanvip** [comment]
问题应该就是Toast直接持有了Activity，Activity finish的时候Toast还未结束导致的。
![Screenshot_20210330-152352](https://user-images.githubusercontent.com/19853475/112950206-9ce9de00-916c-11eb-9fa5-1c060bf9d25f.jpg)

**Comment by HuanTanSheng** [comment]
好的，感谢，将着手修复

**Comment by HuanTanSheng** [comment]
3.1.3已修复
