### ISSUE TITLE
复杂选择情况，动态单一类型，右上角计数问题

### ISSUE THREAD

**Issue by developerzjy** [HuanTanSheng/EasyPhotos#177]
demo中，复杂选择情况，动态单一类型
代码 complexSelector(true, 2, 3) //参数说明：是否只能选择单类型，视频数，图片数
此时选择图片的时候，右上角记录选择数的view中，总数显示的是5，应该显示3。如果选择视频，总数应该显示2

**Comment by Hasiy** [comment]
右上角完成按钮 上1/n 数值是否可以支持隐藏

**Comment by Hasiy** [comment]
@HuanTanSheng

**Comment by HuanTanSheng** [comment]
请使用3.1.4
