### ISSUE TITLE
相册返回不执行onActivityResult

### ISSUE THREAD

**Issue by ChenWorkSpace** [HuanTanSheng/EasyPhotos#18]
在fragment 内启动相册，代码：
 EasyPhotos.createAlbum(getActivity(), false, GlideEngine.getInstance())
  .setCount(9)
 .start(TAKE_PHOTO);
GlideEngine使用的是Wiki中提供的Demo
Glide版本:4.5.0
也没有报错提示
测试机型：小米5s 系统版本7.0（另也使用了华为7.0版本的手机测试，结果相同）
使用之前写的相机功能是正常的，能够执行onActivityResult

**Comment by HuanTanSheng** [comment]
@ChenWorkSpace 
感谢反馈。
根据你的描述我做了个demo测了一下，使用小米note3，并无异常。
希望加Q群288600953交流，以有效解决问题所在。

**Comment by yangsanning** [comment]
@HuanTanSheng 我用的就是小米note3，也是不执行不执行onActivityResult
