### ISSUE TITLE
工程会有内存泄漏

### ISSUE THREAD

**Issue by wzgl5533** [HuanTanSheng/EasyPhotos#19]
不知道作者测试过没有？我的偶尔还会因此产生ANR警告，但程序并没有卡死
泄漏信息：
static AlbumModel.insatnce
reference AlbumModel.callBack
leaks com.huantansheng.easy.photos.ui.EasyPhotosActivity
instance

**Comment by HuanTanSheng** [comment]
@wzgl5533 
了解，感谢反馈。正在处理中~

**Comment by HuanTanSheng** [comment]
@wzgl5533 
该问题已修复，请升级2.2.9版本，再次感谢反馈。
我将关闭该issue，如有其他问题欢迎加Q群288600953进行交流~
