### ISSUE TITLE
bug  过滤图片无效

### ISSUE THREAD

**Issue by guosen** [HuanTanSheng/EasyPhotos#192]
逻辑存在错误 过滤gif无效
如果Setting.showGif  = true ； 存在不是GIF的图片是
会走第三个条件
`
  if (Setting.showGif && isGif) {
                Setting.imageEngine.loadGifAsBitmap(((PhotoViewHolder) holder).ivPhoto.getContext(), uri, ((PhotoViewHolder) holder).ivPhoto);
                ((PhotoViewHolder) holder).tvType.setText(R.string.gif_easy_photos);
                ((PhotoViewHolder) holder).tvType.setVisibility(View.VISIBLE);
                ((PhotoViewHolder) holder).ivVideo.setVisibility(View.GONE);
            } else if (Setting.showVideo && type.contains(Type.VIDEO)) {
                Setting.imageEngine.loadPhoto(((PhotoViewHolder) holder).ivPhoto.getContext(), uri, ((PhotoViewHolder) holder).ivPhoto);
                ((PhotoViewHolder) holder).tvType.setText(DurationUtils.format(duration));
                ((PhotoViewHolder) holder).tvType.setVisibility(View.VISIBLE);
                ((PhotoViewHolder) holder).ivVideo.setVisibility(View.VISIBLE);

            } else {
                Setting.imageEngine.loadPhoto(((PhotoViewHolder) holder).ivPhoto.getContext(), uri, ((PhotoViewHolder) holder).ivPhoto);
                ((PhotoViewHolder) holder).tvType.setVisibility(View.GONE);
                ((PhotoViewHolder) holder).ivVideo.setVisibility(View.GONE);
            }

`

**Comment by HuanTanSheng** [comment]
Setting.showGif = true的作用是显示gif图片，而不是只显示gif图片。
