### ISSUE TITLE
权限问题 

### ISSUE THREAD

**Issue by myadream** [HuanTanSheng/EasyPhotos#194]
机型: 小米 max 
问题: 选择图片已授权, 并且通过 `PermissionUtil.checkAndRequestPermissionsInActivity`  检验返回也是 `true`,  但是在授权页面还是未授权状态.

![image](https://user-images.githubusercontent.com/40756102/126465854-b2a7a1b5-c476-40e1-beb8-e0cb3a8786f3.png)
![image](https://user-images.githubusercontent.com/40756102/126465870-6ec6109b-1a3e-4391-880c-b7f9a17f0dfe.png)
![image](https://user-images.githubusercontent.com/40756102/126465880-2a3b590f-0ac8-4680-8282-f5912f344168.png)
![image](https://user-images.githubusercontent.com/40756102/126465978-9992dd40-d870-460e-b89d-cad89b1a5151.png)

**Comment by windyer39** [comment]
请问下解决了，我也遇到这个问题了。升级到最新版本也不行

**Comment by sagaciousfrog** [comment]
怎么解决的 ,同样问题

**Comment by myadream** [comment]
太久忘记了...

**Comment by hardgit** [comment]
> 请问下解决了，我也遇到这个问题了。升级到最新版本也不行
好兄弟，我也遇到这个问题了，你是怎么解决的
