### ISSUE TITLE
选择页面右上角文本的显示优化---复杂类型且选择互斥时，选择总数能否跟随对应类型的最大值变化

### ISSUE THREAD

**Issue by GeminiR** [HuanTanSheng/EasyPhotos#197]
因为目前选择后的文本显示总数是两数之和，这样也合理的，只是目前需求有遇到就是说可选择视频和图片、但是类型又互斥的情况下，右上角的数字能否跟随所选类型，改变总数为对应媒体类型的最大值

 private void shouldShowMenuDone() {
        if (Result.isEmpty()) {
            if (View.VISIBLE == tvDone.getVisibility()) {
                ScaleAnimation scaleHide = new ScaleAnimation(1f, 0f, 1f, 0f);
                scaleHide.setDuration(200);
                tvDone.startAnimation(scaleHide);
            }
            tvDone.setVisibility(View.INVISIBLE);
            tvPreview.setVisibility(View.INVISIBLE);
        } else {
            if (View.INVISIBLE == tvDone.getVisibility()) {
                ScaleAnimation scaleShow = new ScaleAnimation(0f, 1f, 0f, 1f);
                scaleShow.setDuration(200);
                tvDone.startAnimation(scaleShow);
            }
            tvDone.setVisibility(View.VISIBLE);
            tvPreview.setVisibility(View.VISIBLE);
        }
        if (Setting.complexSelector && Setting.complexSingleType) {
            //如果是复杂选择，且单一类型时，才做该处理
            ArrayList<Photo> results = Result.photos;
            if (results != null && results.size() > 0) {
                boolean isVideo = false;
                for (Photo result : results) {
                    isVideo = result.type.contains("video");
                    break;
                }
                tvDone.setText(getString(R.string.selector_action_done_easy_photos, Result.count(),
                        isVideo ?  Setting.complexVideoCount : Setting.complexPictureCount));
            } else {
                tvDone.setText(getString(R.string.selector_action_done_easy_photos, Result.count(),
                        Setting.count));
            }
        } else {
            tvDone.setText(getString(R.string.selector_action_done_easy_photos, Result.count(),
                    Setting.count));
        }
    }

**Comment by HuanTanSheng** [comment]
请使用3.1.4版本
