### ISSUE TITLE
权限问题

### ISSUE THREAD

**Issue by baiRookie** [HuanTanSheng/EasyPhotos#2]
建议权限请求在跳转之前进行请求

**Comment by HuanTanSheng** [comment]
感谢建议，但是我没太明白你的意思。
是说在跳转到相册之前做运行时权限处理么？
如果是这个意思，那么这个操作就不属于EasyPhotos内部的事情，而是由你来做，在你的button事件中添加权限处理。
我突发奇想，似乎也可以在EasyPhotos的内部做，就是添加一个权限检测的activity，这个activity只处理运行时权限，相当于一个中间页，当获取到权限时跳转到EasyPhotos的相册，没有权限则做重复询问等事情，但是我没想好这样做带来的利弊关系，你有更好的建议么？

**Comment by HuanTanSheng** [comment]
@baiRookie 
感谢建议，但是我没太明白你的意思。
是说在跳转到相册之前做运行时权限处理么？
如果是这个意思，那么这个操作就不属于EasyPhotos内部的事情，而是由你来做，在你的button事件中添加权限处理。
我突发奇想，似乎也可以在EasyPhotos的内部做，就是添加一个权限检测的activity，这个activity只处理运行时权限，相当于一个中间页，当获取到权限时跳转到EasyPhotos的相册，没有权限则做重复询问等事情，但是我没想好这样做带来的利弊关系，你有更好的建议么？

**Comment by baiRookie** [comment]
我的建议是权限请求放到单独类，在调用相机或拍照前调用方法去判断权限，不然在相册内没请求到权限全黑有些不太好

**Comment by HuanTanSheng** [comment]
@baiRookie 
明白了。
EasyPhotos中有一个PermissionUtil类，是我封装的运行时权限处理工具类，你可以看一下，具体使用方式可以参考EasyPhotosActivity这个类中的实现。或者加我微信电话沟通都可以。
你可以在调用相机或相册之前通过这个类来处理运行时权限。
因为运行时权限是绑定Activity回调的，不是能够通过一个方法来解决的问题，而且如果用户不给权限如何处理都需要你来控制，你也可以参考EasyPhotosActivity是如何处理的。
PermissionUtil已经将运行时权限的处理缩减到两个方法（整个类中也只有两个public方法），一个在判断是否有权限的时候用，一个在activity的权限回调中使用，很方便。
希望能够帮助到你。

**Comment by HuanTanSheng** [comment]
@baiRookie 
对了，那个全黑的问题我会在大版本升级的时候通过UI来处理一下，让权限这里更友好。那个时候就不需要你在外面处理了，这个周期会很快的，一个月之内搞定。
