### ISSUE TITLE
紧急：关于拍照返回崩溃问题

### ISSUE THREAD

**Issue by wzgl5533** [HuanTanSheng/EasyPhotos#21]
我把相册里的照片全部删除，然后点击相册（有相机，单选或多选），提示没有符合的图片，拍一张吧。
点击拍照，确认时，返回崩溃（但目录下已经保存图片），当我第二次点击相册（有相机，单选或多选），还是同样的提示：没有符合的图片，拍一张吧。请作者测试一下

**Comment by HuanTanSheng** [comment]
@wzgl5533  
感谢反馈，已修复。
