### ISSUE TITLE
请问，支持选完图片后，再次进入相册，图片记录选中状态

### ISSUE THREAD

**Issue by magiclonw** [HuanTanSheng/EasyPhotos#27]
同题目

**Comment by HuanTanSheng** [comment]
请查看
 https://github.com/HuanTanSheng/EasyPhotos/wiki/02-%E7%9B%B8%E6%9C%BA%E4%B8%8E%E7%9B%B8%E5%86%8C
中的
“相册中包含默认勾选图片地址集合” 和 “相册中包含默认勾选图片集合”

**Comment by magiclonw** [comment]
这个库测试的怎么样了，可以在生产环境使用了么？

**Comment by HuanTanSheng** [comment]
我的项目和很多朋友的项目都已经在用，没有任何问题。
但是安卓的碎片化你懂的，备不住就有哪个莫名机型会有问题，如果发现任何机型异常可以反馈给我，我及时处理。

**Comment by magiclonw** [comment]
嗯，这个我也是从知乎那个库Matisse拐你这里的，上面提的issue基本没怎么改过。
你这里应该在博客上好好写个教程，推广下，让更多人来参与，现在感觉你这里人气还没有起来。

**Comment by HuanTanSheng** [comment]
是啊，实在是精力有限，平时工作内容好多，同时还要维护这个库，另外还有其他事情要做，实在是抽不出或者不想再拿出时间去维护博客了。。。
我只希望把更多的时间去用来完善这个库，当这个库做到一定程度不需要再进行功能更新了，我就会研究博客的事情啦，不过这个时间还有很长，因为这个库还有很多功能没有加，比如图片的编辑、视频的选择等等。

**Comment by magiclonw** [comment]
有个疑问，现在很多都是基本只选图片，然后拍个图片就够了，你的后期加入图片编辑，视频选择，这些功能会让那些只要基础功能的程序比较臃肿，你那里会怎么设计，当然了有些人确实又会用到图片编辑功能，你这里怎么去设计module

**Comment by HuanTanSheng** [comment]
归根结底他是一个多媒体选择器，多媒体包括图片和视频，使用者只需要配置可供选择的多媒体格式就可以。所以图片和视频会在同一个module中。
图片编辑的功能是抄的微信，你可以看一下微信的相册，里面可以进行图片的各种编辑，可以很大程度提升app的体验度，我不认为这是臃肿，反而认为是必要的，一个多媒体选择器应该具备的功能。除了微信的相册，rom的相册，大厂的相册目前基本都有图片编辑的功能。而既然做了这些功能，我当然会把他们做成独立的module，并且会提供对外接口，方便开发者在自己的界面中也可以使用这些功能。
其他的功能嘛，比如添加水印、压缩什么的，其实都是用到图片选择就一定会用到的功能。毕竟拿出图片就是为了展示，展示可能就涉及水印、压缩等，甚至是下载，下载了那就一定会有水印、压缩等需求了。所以根本上来说貌似没有一个项目只需要选一个照片然后就完事儿了，就什么都不做了。所以不必在意这个项目未来添加的功能是否对你来说很臃肿，因为并不是臃肿，而是必要的，你一定会用到的。就算有一些你用不到，也不会因此增加增加多大的Size，充其量几Kb而已

**Comment by HuanTanSheng** [comment]
QQ交流群：288600953

**Comment by magiclonw** [comment]
好的，感谢
