### ISSUE TITLE
报告一个问题，关于glide的版本导致的问题 

### ISSUE THREAD

**Issue by Beiler** [HuanTanSheng/EasyPhotos#3]
glide4.4.0将会导致崩溃：

java.lang.NoSuchMethodError: No virtual method into(Landroid/widget/ImageView;)Lcom/bumptech/glide/request/target/Target; in class Lcom/bumptech/glide/RequestBuilder; or its super classes (declaration of 'com.bumptech.glide.RequestBuilder' appears in /data/app/com.hdl.apsp-1/base.apk:classes4.dex)
                                                                at com.huantansheng.easyphotos.ui.adapter.PhotosAdapter.onBindViewHolder(PhotosAdapter.java:75)

请问，可以使用自定义的GlideEngine()嘛？Glide版本不同导致的问题挺麻烦的。

**Comment by HuanTanSheng** [comment]
@Beiler 
你好，我现在把Glide升级到最新版，升级后会在这里at你，这样能最快解决你的问题(●'◡'●)。
GlideEngine()这个短期内应该不会搞，但是长期计划是有ImageEngine（glide、Picasso、Fresco全支持）的。

**Comment by Beiler** [comment]
加油~挺方便，挺好用的，状态栏背景色是白色要怎么处理？

**Comment by HuanTanSheng** [comment]
@Beiler 
感谢支持，状态栏的颜色除了预览页和拼图页之外，都是和你的app主题一致的。如果你没有做特殊处理的话，应该就是色值 colorPrimaryDark 的颜色

**Comment by Beiler** [comment]
@HuanTanSheng 无法自定义的么，状态栏字体颜色要怎么改变？我app主题确实状态栏背景色是白色，不过我是针对6.0以上是白色，并且字体颜色是黑色，但是在选择图片这里，状态栏是白色，字体也是白色，如果不能修改的话那还是挺不好的。另外，我觉得UI可以放大点，比如拍照按钮，选择按钮。还有一个问题就是gif图片，快速拉到顶部然后连续多拉几次会导致gif图片静止不动，不知道是不是glide的问题。

**Comment by HuanTanSheng** [comment]
@Beiler 
抱歉，内部确实没有考虑白色状态栏切换字体颜色的问题，我会加一个参数来控制状态栏的字体颜色是否改变为黑色。如果你着急的话可以用module的形式引用EasyPhotos，自己先改一下我的代码。我会在三个版本之内处理这个问题。
gif的问题我等一下升级好glide后看一下。

**Comment by Beiler** [comment]
@HuanTanSheng 好的，谢谢你百忙中这么快的回复我的问题。

**Comment by manburenshenglu** [comment]
java.lang.NoSuchMethodError: No virtual method setDecodeFormat(Lcom/bumptech/glide/load/DecodeFormat;)Lcom/bumptech/glide/GlideBuilder; in class Lcom/bumptech/glide/GlideBuilder; or its super classes (declaration of 'com.bumptech.glide.GlideBuilder' appears in /data/app/com.jaagro.driver-xknc3bZdECYOGk_4DQApyA==/base.apk)   这个问题是怎么解决的？？？ glide版本4.11.0
