### ISSUE TITLE
你好，我想要直接跳到这个界面，有办法做到吗，谢谢

### ISSUE THREAD

**Issue by Edwares** [HuanTanSheng/EasyPhotos#30]
![34258f93-6670-47c4-9687-2919a3fa3375](https://user-images.githubusercontent.com/22723537/39026040-6825e248-447d-11e8-85c4-d8ed4dc217a8.png)

**Comment by HuanTanSheng** [comment]
目前来说，这个界面是内部用的，并没有做外部回调，所以即使跳转后也不能供你使用。
未来，我会考虑增加该功能，感谢反馈。

**Comment by Edwares** [comment]
好吧  谢谢
