### ISSUE TITLE
拼接图片中重新选择图片拼接后预览问题

### ISSUE THREAD

**Issue by LRDDYR** [HuanTanSheng/EasyPhotos#31]
不得不说这是个非常好的图片选择库，非常赞👍。有一些小问题：在进入拼一张中重新选择一张图片后保存拼接图片，回到图片选择列表，点击刚拼接的图片，会显示下一张图片而不会显示当前拼接的图片，不过返回是正确的，希望楼主看一下

**Comment by HuanTanSheng** [comment]
@LRDDYR 
非常抱歉，你发Issues时我刚好进入休息阶段，所以回复的晚了，见谅。
我做了测试，并没有复现你发现的问题，希望能加Q群交流：288600953
