### ISSUE TITLE
选择图片状态栏问题

### ISSUE THREAD

**Issue by songsongtao** [HuanTanSheng/EasyPhotos#32]
`当我设置项目<item name="android:windowTranslucentStatus">true</item>
就会出现这种情况`
![tim 20180530154912](https://user-images.githubusercontent.com/20622787/40706795-674c4952-6421-11e8-8989-85d6e8db893a.jpg)
内容跑到了状态栏之上

**Comment by HuanTanSheng** [comment]
最快的解决方案是在你的activity中设置style，而不是在application中设置。

**Comment by HuanTanSheng** [comment]
我会在下一个版本升级中修改这个问题

**Comment by HuanTanSheng** [comment]
我并未发现类似问题，请问你在清单文件里设置EasyPhotosActivity的东西了吗？

**Comment by HuanTanSheng** [comment]
建议加群，方便交流，以尽快解决。288600953 （Q群）

**Comment by songsongtao** [comment]
ppstyle文件设置了statuscolor为白色,然后你库的状态栏颜色就被覆盖了
