### ISSUE TITLE
能否增加文件类型的过滤项？比如相册里只显示视频等等（就是选视频）

### ISSUE THREAD

**Issue by 18872731525** [HuanTanSheng/EasyPhotos#33]
Matisse那边过来的，，，的确有不少明明有人已经提了但是官方却不去完善的地方，
你这个库感觉做的挺用心的， 希望后续能增加类似 文件类型 过滤的配置哈

**Comment by HuanTanSheng** [comment]
@18872731525  感谢支持，后续会增加，只是时间可能会久一些，目前工作比较忙……
另外可以加Q群，共同维护这个库。计划近期将代码重构，分出基础lib和拓展lib的形式，满足各种需求，进群后我们可以一起讨论~
Q群：288600953

**Comment by HuanTanSheng** [comment]
@18872731525 你好，已经支持
