### ISSUE TITLE
重复进入相册，清除上一次已选中的图片，没有完成按钮可保存状态

### ISSUE THREAD

**Issue by yangsanning** [HuanTanSheng/EasyPhotos#37]
第一次进入相册选中图片，第二次通过setSelectedPhotoPaths设置图片进入相册，清空图片，没有保存按钮，退出相册，无法识别是否清除已选择相片

**Comment by HuanTanSheng** [comment]
@yangsanning 抱歉，回复晚了，建议加QQ交流群288600953反馈问题会得到较快回复。
针对这个问题，其实无需识别是否清除已选择相片，因为如果用户没有点击完成，直接返回，是RESULT_CANCELED的回调，如果点了完成，只需要获取带回来的数据即可知道用户选择了哪些图片。
如果已经解决问题，麻烦点击关闭这条issue，如果没有解决，建议加群，效率会高一些，辛苦~

**Comment by yangsanning** [comment]
好的，谢谢
