### ISSUE TITLE
[建议]能否将预览页单独出一个图片预览功能

### ISSUE THREAD

**Issue by zhangchaoxu** [HuanTanSheng/EasyPhotos#45]
目前的预览页功能非常赞
能否单独再加一个预览页面，用来预览图片，在九宫格选中后或者其它场景中使用。
传值是图片的列表，图片可能是url链接，可能是file。
然后在预览页面中可以预览和左右切换。

thanks

**Comment by HuanTanSheng** [comment]
感谢建议，我将重新启动一个框架，满足图片、视频、编辑、整体UI、单页UI、完全自定义UI等需求，大概四五月份完成，敬请期待~

**Comment by zhangchaoxu** [comment]
👍，期待新框架的出现
