### ISSUE TITLE
图片预览，PhotoView 和 RecyclerView 冲突

### ISSUE THREAD

**Issue by SMask** [HuanTanSheng/EasyPhotos#50]
图片预览页面。
PhotoView的双指放大缩小 和 RecyclerView的左滑右滑 冲突

**Comment by HuanTanSheng** [comment]
额……

**Comment by HuanTanSheng** [comment]
额……

**Comment by HuanTanSheng** [comment]
我这里并没有发现EasyPhotos在这个地方有任何问题，当然，不排除我没有理解你的意图，为了真正解决你在使用中遇到的问题，欢迎加入QQ交流群一起交流这个问题，QQ群：288600953
