### ISSUE TITLE
带相机的图库，相机图标能否放在第一张图片的位置

### ISSUE THREAD

**Issue by sicelex** [HuanTanSheng/EasyPhotos#59]
带相机的图库，目前相机图标是悬浮的，如何做成像知乎相机一样在第一个图片的位置？

**Comment by HuanTanSheng** [comment]
目前想达到这种效果，只能通过修改代码的方式实现，建议clone尝试

**Comment by HuanTanSheng** [comment]
@HystrixWong 你好，很高心地通知你，相机图标已经能够通过配置放在第一张图片的位置了
