### ISSUE TITLE
能否把图片使用库改成接口，然后自己选择用Glide还是Picasso，以及其它？

### ISSUE THREAD

**Issue by Berial** [HuanTanSheng/EasyPhotos#6]

**Comment by HuanTanSheng** [comment]
@Berial 
你好，是有这个计划的。
会支持Glide、Picasso、fresco。
但是给不了具体时间，年底公司任务太强，希望理解。
目前EasyPhotos的Glide部分是216Kb，也就是最终安装包会因为Glide的问题增加216KB，希望你能够忍一忍，我会尽快处理这个问题，感谢反馈。

**Comment by Berial** [comment]
不是体积的事，比如其他库用了个3.x的glide，你这个库就用不了了

**Comment by HuanTanSheng** [comment]
@Berial 
感谢反馈，这确实是致命的，也是我所忽略的。
我将在本月月末之前解决这个问题，并发布新版以供使用。
再次感谢！

**Comment by HuanTanSheng** [comment]
@Berial 
已经更新版本，使用接口形式绑定图片加载框架。
欢迎使用~~~///(^v^)\\\~~~

**Comment by HuanTanSheng** [comment]
@Berial 
已经更新版本，使用接口形式绑定图片加载框架。
欢迎使用~~~///(^v^)\~~~
