### ISSUE TITLE
希望相机图标能配置是否放在第一张图片

### ISSUE THREAD

**Issue by maeao** [HuanTanSheng/EasyPhotos#60]

**Comment by HuanTanSheng** [comment]
你好，该功能会在后续添加，但时间会较晚，如果急用，建议下载源码自行修改。
当然，如果你愿意，欢迎成为EasyPhotos的贡献者，直接解决该问题。
EasyPhotos交流群QQ号：288600953

**Comment by HuanTanSheng** [comment]
@Masksam 你好，很高心地通知你，相机图标已经能够通过配置放在第一张图片的位置了
