### ISSUE TITLE
小建议

### ISSUE THREAD

**Issue by tanzhihao1qaz** [HuanTanSheng/EasyPhotos#62]
当选中的图片为0时，右上角的确定按钮其实可以不用隐藏，因为目前感觉框架是只能添加图片，不能删除

**Comment by tanzhihao1qaz** [comment]
虽然我能通过resultCode间接删除图片，但是对于用户来说，他们是不知道点返回键就代表删除图片

**Comment by HuanTanSheng** [comment]
欢迎加入我们的QQ交流群一起讨论：288600953
