### ISSUE TITLE
Can support only select GIF images, other format images are not displayed are filtered？

### ISSUE THREAD

**Issue by GoldenCR7** [HuanTanSheng/EasyPhotos#64]
Can support only select GIF images, other format images are not displayed are filtered？

**Comment by joker-fu** [comment]
ok 后续支持

**Comment by GoldenCR7** [comment]
If supported, we will recommend your library to GIPHY's R&D team.

**Comment by HuanTanSheng** [comment]
@GoldenCR7 It is already supported in version 2.4.3,and welcome to join our QQ exchange group: 288600953

**Comment by GoldenCR7** [comment]
> @GoldenCR7 It is already supported in version 2.4.3,and welcome to join our QQ exchange group: 288600953

I have already recommended your open source library to Giphy, I hope that your open source project will be better and better, and get more sponsorship.
