### ISSUE TITLE
图片加载慢

### ISSUE THREAD

**Issue by Ymmmsick** [HuanTanSheng/EasyPhotos#68]
机型：mix2
android版本:8.0
EasyPhoto版本:2.4.3
图片数量:1W6

退回到2.4.1版本加载速度明显快很多，大概1秒左右就能加载出来，在2.4.1+版本上就加载很慢，大概半分钟才加载出来，希望能帮忙看看。

**Comment by joker-fu** [comment]
你是指图片读取的速度？有个2.4.2试过没？

**Comment by Ymmmsick** [comment]
已经找到问题

**Comment by Founder005** [comment]
请问咋解决的

**Comment by Ymmmsick** [comment]
> 请问咋解决的

太久了，这个应该是我们自己原因造成的，所以直接主动关闭了。
