### ISSUE TITLE
有智能压缩功能就好了

### ISSUE THREAD

**Issue by talentju** [HuanTanSheng/EasyPhotos#7]
rt

**Comment by HuanTanSheng** [comment]
@talentju  
在考虑这个功能，因为LuBan的相应功能和LuBan的各种拓展库对这方面已经做的很好了，所以没有急着加。
当然，LuBan及其相应拓展库也具备一些使用问题（但影响不大，主要是长图压缩会模糊和多图可能oom）。
所以EasyPhotos可能会以NDK的方式实现图片的压缩。
在此之前建议使用LuBan或其拓展库（在使用中避免长图和多图，也不排除某些拓展库解决了这些问题），EasyPhotos会在3月之前加入该功能（不排除这个月就会加入的可能，主要还是看我的工作量，你可以来QQ交流群：[288600953](https://jq.qq.com/?_wv=1027&k=5QGgCDe)，升级后会在群里通知），敬请期待~~~///(^v^)\\\~~~

**Comment by alanforgithub** [comment]
要是在把图片裁剪功能加上更完美了^_^

**Comment by HuanTanSheng** [comment]
@alanforgithub  
该功能在计划中，可以加Q群交流：288600953
