### ISSUE TITLE
原图功能怎么用 有处理图片压缩吗

### ISSUE THREAD

**Issue by JamesGZM** [HuanTanSheng/EasyPhotos#74]
rt

**Comment by HuanTanSheng** [comment]
原图功能只是判定用户是否选择了原图，EasyPhotos并没有处理图片压缩。

**Comment by HuanTanSheng** [comment]
设置原图按钮：
setOriginalMenu(isChecked, isVip, "该功能为VIP会员特权功能")//参数说明：是否默认选中，是否可用，不可用时用户点击将toast信息。不执行该方法则不显示原图按钮。是否默认选中可以根据EasyPhotos的回调走，回调中会给出用户上一次是否选择了原图选项的标识

**Comment by HuanTanSheng** [comment]
如需压缩可以使用LuBan这款框架
