### ISSUE TITLE
2.4.6版本添加到项目会失败appComponentFactory 

### ISSUE THREAD

**Issue by Arthurshen98** [HuanTanSheng/EasyPhotos#75]
2.4.6版本添加到项目会失败，2.4.5的没问题，但是2.4.5打开相机就崩溃，华为honor10 系统android 9.0
Error:
	Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.0.1] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:69:5-259:19 to override.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed with multiple errors, see logs

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s

**Comment by HuanTanSheng** [comment]
你好，2.4.6版本是androidx版本，需要你的项目支持androidx

**Comment by HuanTanSheng** [comment]
2.4.5是支持原来support包的，你打开相机就崩溃，应该是没有配置fileprovider吧，看一下wiki和demo是怎么配置的。
