### ISSUE TITLE
为什么相册内的有些图片加载不出来？

### ISSUE THREAD

**Issue by Andy957** [HuanTanSheng/EasyPhotos#77]
如题，手机自带相册内有四张图片，QQ 微信选图也是四张，为什么使用这个相册选择只有两张呢？

**Comment by HuanTanSheng** [comment]
你好，麻烦提供一下没有显示出来的图片信息，比如文件大小，像素，名字等，以便排查，感谢🙏

**Comment by Andy957** [comment]
您好。我这样写代码对吗？还是说还需要专门的去设置显示什么样的图片？
![QQ截图20190714125354](https://user-images.githubusercontent.com/52651185/61179513-9503a680-a636-11e9-88f6-5d256454f3ce.png)

**Comment by joker-fu** [comment]
@Andy957 EasyPhotos 默认最小文件大小为1 宽高为1
