### ISSUE TITLE
长图看不清文字

### ISSUE THREAD

**Issue by leaderliang** [HuanTanSheng/EasyPhotos#78]
大佬，库写的很不错；不过对于相册里的长图会看不清文字，这个有好的处理方式么
![3281563450832_ pic_hd](https://user-images.githubusercontent.com/3939753/61455469-3328a100-a996-11e9-9060-3e68fbb872f6.jpg)

**Comment by leaderliang** [comment]
这个是原图


![Screenshot_2019-06-03-11-49-29-582_com manymanycoin android](https://user-images.githubusercontent.com/3939753/61455795-28224080-a997-11e9-9887-ba4f45bc72b3.png)

**Comment by HuanTanSheng** [comment]
不好意思，才给你回复

**Comment by HuanTanSheng** [comment]
@leaderliang

**Comment by HuanTanSheng** [comment]
@leaderliang 该问题已解决，请使用2.4.8版本
