### ISSUE TITLE
项目存在内存泄漏问题

### ISSUE THREAD

**Issue by lcyluo** [HuanTanSheng/EasyPhotos#79]
下载源码编译运行后，会经常有内存泄漏提示；
是否考虑支持图片编辑功能（涂鸦，剪裁等效果）；

**Comment by HuanTanSheng** [comment]
你好，内存泄露麻烦提供一下截图，因为我这边的Leaks没有报内存泄漏。

**Comment by HuanTanSheng** [comment]
因目前手头工作太忙，图片编辑功能（涂鸦，剪裁等效果）暂时不会加，剪裁建议用Ucrop。

**Comment by lcyluo** [comment]
![Screenshot_2019-07-25-13-40-00-201_com huantanshe](https://user-images.githubusercontent.com/5035536/61849259-4205db00-aee3-11e9-8858-0f950cf7de8f.png)
![Screenshot_2019-07-25-13-39-44-081_com huantanshe](https://user-images.githubusercontent.com/5035536/61849268-47fbbc00-aee3-11e9-99b5-5e7a324f0c36.png)
![Screenshot_2019-07-25-13-39-40-001_com huantanshe](https://user-images.githubusercontent.com/5035536/61849275-4af6ac80-aee3-11e9-9fad-73e790a12d52.png)

小米mix2s MIUI 10.3.2

**Comment by HuanTanSheng** [comment]
不好意思，你能把加号打开，看一下具体是哪里产生的泄露么？

**Comment by HuanTanSheng** [comment]
我这里复现不出来，所以需要麻烦你一下，感谢

**Comment by HuanTanSheng** [comment]
是因为广告view产生的泄露，我会进行修复，感谢你的反馈。

**Comment by HuanTanSheng** [comment]
如果不使用广告功能的话，是没有问题的

**Comment by lcyluo** [comment]
好的，谢谢；

**Comment by lcyluo** [comment]
已修复；非常感谢！
