### ISSUE TITLE
Demo中缺少类吧！

### ISSUE THREAD

**Issue by DevXue** [HuanTanSheng/EasyPhotos#8]
刚下载的demo  导入到斯丢丢中，发现没有GlideApp这个类。
![error](https://user-images.githubusercontent.com/9455329/35022832-e59bbe36-fb72-11e7-8c7a-7f5bc6b8e557.png)

**Comment by HuanTanSheng** [comment]
@DevXue 
这个是Glide自动生成的，我现在重新下一个Demo检查一下，稍后回复。

**Comment by HuanTanSheng** [comment]
@DevXue 
感谢反馈，现已修复，请重新下载Demo或在本地修改此类，把GlideApp改为Glide，并去除GlideApp的import。
![image](https://user-images.githubusercontent.com/17489136/35024405-3a05e2a6-fb7a-11e7-8422-426693b65206.png)
thisAppGlideModule可以删除了。
期待star，期待入群交流~~~///(^v^)\\\~~~

**Comment by HuanTanSheng** [comment]
@DevXue 
如果仍有问题，随时交流。
如果这个问题经过测试解决了，还要麻烦您关闭这个issue，这样我就知道确实解决了，谢谢。

**Comment by DevXue** [comment]
@HuanTanSheng   老哥，这个项目真棒！！   希望你一直维护下去！ 已经start。
