### ISSUE TITLE
由于上一个版本修改预览大图，会导致相册现在预览图片时，图片向左旋转90度。

### ISSUE THREAD

**Issue by lcyluo** [HuanTanSheng/EasyPhotos#80]
如题；holder.ivLongPhoto.setImage(ImageSource.uri(path)); 应该是这句代码导致的；

**Comment by lcyluo** [comment]
部分图片向左旋转90度，不是所有的。

**Comment by HuanTanSheng** [comment]
已修复，麻烦下载一下demo文件，帮忙确认是否修复成功，感谢

**Comment by lcyluo** [comment]
已修复，非常感谢！
