### ISSUE TITLE
怎么获取原图呢？

### ISSUE THREAD

**Issue by workertao** [HuanTanSheng/EasyPhotos#81]
怎么获取原图呢？没找到获取原图的方法，点击demo的原图按钮，貌似没用。

**Comment by HuanTanSheng** [comment]
@workertao 路径就是原图路径
那个原图选项，只是一个标识，如果你的业务需要了解用户是否要求选择上传原图，就用这个，没有的话就不用，一般业务都不用，都得压缩一下。
EasyPhotos本身没有压缩，压缩的话建议用luban，如果用户点了原图，你可以上传原路径图片，如果没点原图，你可以压缩后上传。

**Comment by workertao** [comment]
收到，谢谢
