### ISSUE TITLE
预览页面的状态栏和Actionbar颜色不一致，看起来很难看啊

### ISSUE THREAD

**Issue by Hiboboo** [HuanTanSheng/EasyPhotos#82]
效果图：
![device-2019-08-03-180952](https://user-images.githubusercontent.com/11403290/62410587-0d4bff00-b61a-11e9-9584-145fb1f22f3a.png)
没错，状态栏颜色和Actionbar颜色都是白色的。
### **求解！！！**

**Comment by HuanTanSheng** [comment]
emmm，好尴尬，但是吧，我就是这样设计的……
如果想要修改，建议下载源码自行改动，因为我近期有其他该框架升级计划，这个的话，可能要很久才能支持api自定义
