### ISSUE TITLE
希望增加拍摄视频功能

### ISSUE THREAD

**Issue by Jarvis-Lau** [HuanTanSheng/EasyPhotos#83]
用了一下您的EasyPhotos库，目前非常稳定好用，但是相机按钮没法拍摄视频，希望能出增加一个拍摄视频的功能

**Comment by HuanTanSheng** [comment]
@Jarvis-Lau 你好，非常抱歉，回复的有些晚，最近实在太忙碌，你可以加交流群，已经有群友拓展了该功能。q群：288600953
