### ISSUE TITLE
为什么不支持图片裁剪呢？

### ISSUE THREAD

**Issue by jianglan666** [HuanTanSheng/EasyPhotos#85]
强烈建议加上

**Comment by HuanTanSheng** [comment]
@jianglan666 裁剪建议集成Ucrop，在EasyPhotos返回数据后启动Ucrop就好了，即灵活又简单

**Comment by jianglan666** [comment]
> @jianglan666 裁剪建议集成Ucrop，在EasyPhotos返回数据后启动Ucrop就好了，即灵活又简单

这样还得集成两个库，虽然已经集成了吧^_^
