### ISSUE TITLE
android10无法预览相册

### ISSUE THREAD

**Issue by L1063484547** [HuanTanSheng/EasyPhotos#86]

**Comment by HuanTanSheng** [comment]
已修复

**Comment by L1063484547** [comment]
并没有啊，我在android10的机器上依然无法预览相册 targetversion升级到29

**Comment by HuanTanSheng** [comment]
你可以尝试用demo运行，如果demo没有问题，那么就是你代码的问题，可以参照wiki和demo源码，对你的代码进行修复。

**Comment by L1063484547** [comment]
我就是直接跑的demo

**Comment by HuanTanSheng** [comment]
最新的demo么？你是真机么？在真机上是没问题的呀

**Comment by L1063484547** [comment]
是在真机上的，一加七pro  刚刷的最新android10系统

**Comment by L1063484547** [comment]
你在真机上卸载重装试试

**Comment by HuanTanSheng** [comment]
@L1063484547 你好，经过交流群多位群友测试，确实在某些机型上的安卓10是不好用的，不过幸好，目前已经全部适配，欢迎使用~

**Comment by Qiang11** [comment]
p30还是不行啊，图片有时候显示不出来，有时候显示不全
