### ISSUE TITLE
关于华为 nova 5i pro 相机问题

### ISSUE THREAD

**Issue by ChampionCatLi** [HuanTanSheng/EasyPhotos#87]
作者您好非常感谢此库给我提供的帮助。

复现：运行此刻 最新的DEMO 在同事的华为 nova 5i pro 手机上，点击相机 ，点击返回。
问题:  DEMO首先 会在相机页面停留4-5S，然后黑屏2-3S，之后出现白屏，最后回到DEMO 首页。

android version： 9
emui version : 9.1.1

没有接收到相关的log输出。

**Comment by HuanTanSheng** [comment]
你好，因为没有log，我也没有测试机，所以麻烦你加一下QQ交流群：[288600953](https://jq.qq.com/?_wv=1027&k=5QGgCDe)    ，这样解决起来比较方便~
