### ISSUE TITLE
预览一些比较高的图片的时候，图片头部会超出Toolbar，感觉图片漏出来了一样

### ISSUE THREAD

**Issue by Leu-Z** [HuanTanSheng/EasyPhotos#9]
预览一些比较高的图片的时候，图片头部会超出Toolbar，感觉图片漏出来了一样。就是图片的上部分把状态栏挡住了，但是下面的Toolbar还在，感觉很奇怪——红米Note3

Ps:希望能加上视频选择功能。

**Comment by HuanTanSheng** [comment]
@Leu-Z 
额，尴尬了，预览页是故意这么设计的，你不觉得很酷么？
这样吧，回头把这个变成自定义的效果，可以正常填充颜色，也可以像现在这样。
视频选择在计划之内，敬请期待~
也可以加QQ交流群 [288600953](https://jq.qq.com/?_wv=1027&k=5A111Ir)，我会根据群友的呼声给我的更新计划排期，期待你的加入~~~///(^v^)\\\~~~

**Comment by Beiler** [comment]
@HuanTanSheng 哈哈哈，我就说了吧，这种看着很奇怪，看来并不是我一个人这么觉得，嘿嘿嘿

**Comment by Leu-Z** [comment]
现在开源的图片选择库很多，但是没有一个是特别完美的，总有这样那样的问题，加油哦 @HuanTanSheng

**Comment by HuanTanSheng** [comment]
@Leu-Z 
嗯，就是因为这个原因，才会有EasyPhotos的诞生。
当然，EasyPhotos还有很多不足，因为它太年轻了，才诞生不久。
希望半年之内能把它应有的功能全部搭建完毕吧。
