### ISSUE TITLE
选择过滤只显示视频时，拍照按钮无法显示

### ISSUE THREAD

**Issue by lcyluo** [HuanTanSheng/EasyPhotos#94]
此处能否显示拍照按钮，点击效果为跳转相机视频拍摄页面；

**Comment by lcyluo** [comment]
我查看了代码，找到了问题所在，只是现在有个需求，要求选择视频时，能够点击拍照跳转系统相机录制视频；我在视频录制后，返回Photo对象时crash。需要再研究一下

**Comment by HuanTanSheng** [comment]
你好，EasyPhotos本身不支持录制视频，如需支持，需要修改源码。

**Comment by HuanTanSheng** [comment]
未来应该会支持该功能，但具体时间不确定，见谅

**Comment by lcyluo** [comment]
好的，谢谢，已经大概处理了一下，后续关注您的更新！
