### ISSUE TITLE
请问Manifest中显式声明android:allowBackup="true"是什么考虑呢？

### ISSUE THREAD

**Issue by XuQK** [HuanTanSheng/EasyPhotos#95]
因为今天集成的时候，我在工程里设置了android:allowBackup="false"，然后提示冲突了，要用tools:replace覆盖掉。
我知道怎么解决，只是想知道大佬这样写是不是有什么考虑

**Comment by HuanTanSheng** [comment]
这个是默认生成的，可以修改覆盖
