### ISSUE TITLE
File file = new File(str);

### ISSUE THREAD

**Issue by wpsmgkn** [HuanTanSheng/EasyPhotos#96]
File file = new File(str);   在安卓10用不了， 怎么解决

**Comment by wpsmgkn** [comment]
想做文件上传，但是都报错   权限已经查看过了， 是有的
java.io.FileNotFoundException: /storage/emulated/0/Pictures/1571638744683.jpg: open failed: EACCES (Permission denied)

**Comment by HuanTanSheng** [comment]
用uri的方式
