### ISSUE TITLE
单选模式

### ISSUE THREAD

**Issue by qiushui95** [HuanTanSheng/EasyPhotos#97]
单选模式能否设置直接返回。谢谢开源

**Comment by HuanTanSheng** [comment]
@qiushui95 抱歉，能否详细描述需求？

**Comment by qiushui95** [comment]
我只需要选择一张图片的时候，点击之后直接返回，不用再去点确定

**Comment by HuanTanSheng** [comment]
目前不支持

**Comment by qiushui95** [comment]
@HuanTanSheng 我知道现在不支持，后期是否有计划支持？

**Comment by HuanTanSheng** [comment]
@qiushui95 这个不敢保证，未来有可能会支持，但短时间内应该不会支持，因为现在工作项目太忙，基本除了bug修复，三四个月之内不会进行其他维护。建议你用导入module的方式，自行修改。

**Comment by qiushui95** [comment]
@HuanTanSheng 好的  我现在也忙，等我忙完这个阶段，我改了提个PR。
