### ISSUE TITLE
我想修改Toast提示的文字，有什么办法可以修改吗？

### ISSUE THREAD

**Issue by WarriorYu** [HuanTanSheng/EasyPhotos#99]
1.我想修改Toast提示的文字，有什么办法可以修改吗？  默认的提示是：最多只能选择n张图片或视频，我的需求是提示：最多只能选择n张图片。
2.想把选择照片文件夹的按钮，放到标题栏的正中间，这个UI是不是只能copy源码，自己修改了？

**Comment by HuanTanSheng** [comment]
1、看wiki自定义部分

**Comment by HuanTanSheng** [comment]
2、是的

**Comment by q88qaz** [comment]
> 1、看wiki自定义部分

并没有看到修改吐司的方法

**Comment by HuanTanSheng** [comment]
用3.0.6吧
